package ua.company.model.entity;

import java.io.Serializable;

/**
 * Created by Владислав on 25.09.2017.
    Interface for identified objects.
 */
public interface Identified <PK extends Serializable > {

    /**
     * Method returns id of object which generated by BD;
     * @return
     */
    public PK getPK();
}
